import type { Router } from './router.ts';
import type { Deps } from './lib/types.ts';
import { get_root, get_health, patch_root } from './routes/root.ts';
import { list_types_route, create_type_route, get_type_route, patch_type_route, delete_type_route, list_type_sections_route } from './routes/types.ts';
import { list_sections_route, get_section_route, create_section_route, patch_section_route, move_section_route, delete_section_route, list_children_route, list_ancestors_route, list_section_refs_route } from './routes/sections.ts';
import { list_refs_route, create_ref_route, get_ref_route, delete_ref_route } from './routes/refs.ts';
import { graph_route } from './routes/graph.ts';
import { search_route } from './routes/search.ts';
import { batch_route } from './routes/batch.ts';
import { print_route } from './routes/print.ts';
import { list_section_revisions_route, get_section_revision_route } from './routes/sections-revisions.ts';
import { restore_section_revision_route } from './routes/sections-revisions-restore.ts';
import { list_section_comments_route, get_comment_route } from './routes/comments-list.ts';
import { create_comment_route, patch_comment_route } from './routes/comments-mutate.ts';
import { delete_comment_route } from './routes/comments-delete.ts';
import { list_notebook_comments_route } from './routes/comments-global.ts';
import { list_notebook_history_route } from './routes/history.ts';

export const register_routes = (router: Router, deps: Deps): void => {
  router.add('GET', '/api', get_root(deps));
  router.add('PATCH', '/api', patch_root(deps));
  router.add('GET', '/api/health', get_health(deps));
  router.add('GET', '/api/types', list_types_route(deps));
  router.add('POST', '/api/types', create_type_route(deps));
  router.add('GET', '/api/types/:slug', get_type_route(deps));
  router.add('PATCH', '/api/types/:slug', patch_type_route(deps));
  router.add('DELETE', '/api/types/:slug', delete_type_route(deps));
  router.add('GET', '/api/types/:slug/sections', list_type_sections_route(deps));
  router.add('GET', '/api/sections', list_sections_route(deps));
  router.add('POST', '/api/sections', create_section_route(deps));
  router.add('GET', '/api/sections/:slug', get_section_route(deps));
  router.add('PATCH', '/api/sections/:slug', patch_section_route(deps));
  router.add('DELETE', '/api/sections/:slug', delete_section_route(deps));
  router.add('GET', '/api/sections/:slug/children', list_children_route(deps));
  router.add('GET', '/api/sections/:slug/ancestors', list_ancestors_route(deps));
  router.add('GET', '/api/sections/:slug/refs', list_section_refs_route(deps));
  router.add('GET', '/api/sections/:slug/revisions', list_section_revisions_route(deps));
  router.add('GET', '/api/sections/:slug/revisions/:rev', get_section_revision_route(deps));
  router.add('POST', '/api/sections/:slug/revisions/:rev/restore', restore_section_revision_route(deps));
  router.add('POST', '/api/sections/:slug/move', move_section_route(deps));
  router.add('GET', '/api/refs', list_refs_route(deps));
  router.add('POST', '/api/refs', create_ref_route(deps));
  router.add('GET', '/api/refs/:id', get_ref_route(deps));
  router.add('DELETE', '/api/refs/:id', delete_ref_route(deps));
  router.add('GET', '/api/sections/:slug/comments', list_section_comments_route(deps));
  router.add('POST', '/api/sections/:slug/comments', create_comment_route(deps));
  router.add('GET', '/api/comments', list_notebook_comments_route(deps));
  router.add('GET', '/api/history', list_notebook_history_route(deps));
  router.add('GET', '/api/comments/:id', get_comment_route(deps));
  router.add('PATCH', '/api/comments/:id', patch_comment_route(deps));
  router.add('DELETE', '/api/comments/:id', delete_comment_route(deps));
  router.add('GET', '/api/graph', graph_route(deps));
  router.add('GET', '/api/search', search_route(deps));
  router.add('POST', '/api/batch', batch_route(deps));
  router.add('GET', '/print', print_route(deps));
};
